### ISSUE TITLE
Reached EOF for stream Mqtt error

### ISSUE THREAD

**Issue by salmanzafar40** [karpy47/php-mqtt-client#10]
Hi i'm getting this error when i add ca file
> MQTT: Opening socket to: tcp://35.165.61.173:1884 MQTT: Sending CONNECT MQTT: Reached EOF for stream MQTT: Closing socket MQTT: Connection failed! Error: 0 error

i have tested it on local server and it is working fine but when i try to connect to live server it is throwing the error above

**Comment by karpy47** [comment]
Sounds like something is wrong with the certificate. Can be tricky to get right. Double check that the cert is set up correctly server side.

**Comment by salmanzafar40** [comment]
Yup.
i got it the host name  was different so i have to add it manually in /etc/hosts file.|
Btw Thank you :+1:
