### ISSUE TITLE
Autmatic sync with packagist does not seem to work

### ISSUE THREAD

**Issue by tobbexiv** [karpy47/php-mqtt-client#17]
As the latest version on packagist is v1.0.1 from August 2017, I use dev-master for now. However, this also does not always have the latest changes included. For example, now the dev-master version on packagist is from 2019-01-12 07:05 UTC and all changes done later are not included. Could you please check whether you GitHub webhook is working properly or set up one if you do not have one?

Thank you :)

**Comment by karpy47** [comment]
Trying to activate service in GitHub but something is missing... waiting for support.

**Comment by karpy47** [comment]
Fixed now.

**Comment by tobbexiv** [comment]
Thanks a lot. Also for releasing the new version!
