### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by ErenPhayte** [karpy47/php-mqtt-client#2]
Hi,

Please update the name spacing to standards. The namespacing is causing issues because it contains - character

**Comment by karpy47** [comment]
Could you please leave a link to the standard you are referring to. I'll check it out.

**Comment by ErenPhayte** [comment]
Hi!

here you go https://www.php-fig.org/psr/psr-4/

**Comment by karpy47** [comment]
Updated namespace and fixed a few bugs...
