### ISSUE TITLE
Error 0?

### ISSUE THREAD

**Issue by piyushmanolkar** [karpy47/php-mqtt-client#22]
Please Check Out the Gist link [HERE](https://gist.github.com/TickleMaPickle/3a20a0a88ee6ed57ca0ee6d89214fe45)

**Comment by karpy47** [comment]
To me this suggest a server side problem. There is a stream opened, but you're not getting the expected response before the stream timeouts. Please check that the MQTT server at the other end receives the connect message and sends a connect acknowledge. (Debug mode?) 
Encryption is optional, depends on how your server was setup. Start without to reduce complexity, as you do now.

**Comment by piyushmanolkar** [comment]
Thanks, Will get back to you ASAP. One more thing can you add support for MQTT 5?
And if i want the encryption which .pem file to use? I have two pem files.

**Comment by karpy47** [comment]
Well... use the pem with the private key?
