### ISSUE TITLE
Requests extremely slow

### ISSUE THREAD

**Issue by ArnaudLier** [karpy47/php-mqtt-client#28]
Hello, all I want to do is to send a message to a topic
and receive the response who is actually stored in another topic
What I did for the moment is that : ```php
$peripheral = $request->route(\'peripheral\');
$client = new MQTTClient(\'my.mqtt.domain\', 1883);
$success = $client->sendConnect(uniqid());
$status = NULL;
$espStatus = NULL;
if ($success) {
    $client->sendSubscribe($peripheral . \'/out\');
    $client->sendPublish($peripheral . \'/in\', \'$\');
    $messages = $client->getPublishMessages();
    foreach ($messages as $message) {
        $status = json_decode($message[\'message\'], true);
    }
    $client->sendDisconnect();
} else {
    echo \'Not able to connect to the main server, aborting...\';
}
```
Is there any way to speed up the process?

**Comment by karpy47** [comment]
Hi,
Don't understand exactly what is slow, but assume you're referring to the socket timeout that is 5 sec by default. You may change this to something else when connecting (see the sendConnect call). The package is however blocking and there will be some delay. PHP is (IMHO) not well suited for non-blocking (threaded) work. In my application I have a cron-job setup to check the MQTT-server every minute, so a few seconds of delay does not matter.
