### ISSUE TITLE
Reached EOF for stream MQTT: Closing socket MQTT: Connection failed! Error: 0

### ISSUE THREAD

**Issue by chakya** [karpy47/php-mqtt-client#29]
I got this error

```MQTT: Opening socket to: tcp://xxx.yyy.com:8883 MQTT: Sending CONNECT 1MQTT: Reached EOF for stream MQTT: Closing socket MQTT: Connection failed! Error: 0

$client->setEncryption('amazonRootCA1.pem');
$client->setClientEncryption('certificate.pem.crt','private.pem.key');
```

I've checked all the cert and nothing is wrong it is working when I use it with mqtt.fx

**Comment by karpy47** [comment]
Sounds strange. Try increasing the timeout when calling sendConnect. 
The client did not get an ACK from the server on the CONNECT message before timeout occured.

**Comment by chakya** [comment]
Does the TLS support pem format?

**Comment by karpy47** [comment]
Yes, use it myself. Try a faulty cert to see if you get same response.
