### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by keiron77** [karpy47/php-mqtt-client#33]
In the function sendConnect() the following lines cause us problems as the server we are using allows different characters and a longer string length:

```
	    if(preg_match("/[^0-9a-zA-Z]/",$clientId)) {
	        $this->debugMessage('ClientId can only contain characters 0-9,a-z,A-Z');
	        return false;
	    }
	    if(strlen($clientId) > 23) {
	        $this->debugMessage('ClientId max length is 23 characters/numbers');
	        return false;
	    }
```

I suggest having this as an option or removing it altogether.

**Comment by karpy47** [comment]
The MQTT v3.1.1 standard says: "The Server MUST allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length, and that contain only the characters "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".
Thus, a server accepting anything else is not compliant and would make me wonder what else is different. 

However, I understand the need and having an option might be good. Could you please submit a merge using an optional property like allowAnyClientID (default false) ignoring chars and length?
