### ISSUE TITLE
Would it be possible to create an Example folder?

### ISSUE THREAD

**Issue by marcelhcb** [karpy47/php-mqtt-client#34]
I have doubts about the correct use of the library. For example I miss the usual "loop" or "ForEverLoop" methods defined in other libraries.
How is it supposed to be used with PhpMqttClient?

**Comment by karpy47** [comment]
Well, this library is not triggered by events so you have to design your own "loop". To me it makes most sense to use this library for frequent checks of a MQTT-server, ie not continously to get messages as they are published on the server. For example when running a cron-job to check a MQTT-server and respond to messages.

**Comment by marcelhcb** [comment]
Thanks. Some additional examples on how to use the api would be great anyway :)
