### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by simion-chis** [karpy47/php-mqtt-client#6]
https://github.com/karpy47/PhpMqttClient/blob/bf0312502732c98258f35d2a04de1c3915482972/MQTTClient.php#L6

```namespace karpy47/PhpMqttClient;``` should be ```namespace karpy47\PhpMqttClient;```

also, I can get the last version only with ```"minimum-stability": "dev"``` in my composer.json

Thanks! 
Simion

**Comment by karpy47** [comment]
Please confirm that it is solved

**Comment by simion-chis** [comment]
Yes. Then namespace it is ok but also in line 1 ```<?PHP``` should be ```<?php``` according to PSR-1.
