### ISSUE TITLE
Cut message content for QoS 0

### ISSUE THREAD

**Issue by tobbexiv** [karpy47/php-mqtt-client#8]
https://github.com/karpy47/PhpMqttClient/blob/826dc76d36c6baa427d2e9a132f7b9ad0d3d1d5b/MQTTClient.php#L1008

In this line you assume that you always need to skip the packet id and payload length. However, this is not correct for QoS 0 messages according to the standard, they do not have a packet id: http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#publish
Also, I am not sure whether there is a payload length as you skip only two characters which in ASCI are two bytes.

I tested this with mosquitto and don't know about Active MQ.

As a result, for QoS 0 messages, the payload is cut by the first two characters / bytes. For QoS 1, everything works fine.

Edit: Of course, for QoS 0 messages the packet id is also wrong as it is derived from the first two characters of the payload.

**Comment by Potas444** [comment]
I solved this with:
```
1010 //	    $message = substr($packet, 2);   // skip packet id (2 bytes) and payload length (2 bytes)
1011            $message = $packet;
```

**Comment by tobbexiv** [comment]
Yes, but this will not work for QoS other than 0. So, you need to consider the QoS also and use one or the other approach depending on which QoS you have.

**Comment by miquelbotanch** [comment]
I've been able to use this class  to correctly read values from MQTT Broker.
Is super cool to be able to store information in a database based at defined hours with a simple crontab.
I'm looking at the protocol to patch the code to adapt it to different levels of QOS

**Comment by karpy47** [comment]
Thanks for finding this! Check the standard and updated the code accordingly.
